---
postgresql:
  enabled: true
  primary:
    persistence:
      size: 1Gi

dendrite_config:
  global:
    server_name: "localhost"

ingress:
  enabled: true

# dashboard is an ConfigMap with labels - it does not harm on testing
grafana:
  dashboards:
    enabled: true
