# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- task: CmdLine@2
  displayName: 'List all directories'
  inputs:
    script: |
      echo "Structure of work folder of this pipeline:"
      tree $(Agent.WorkFolder)\1 /f
      echo "Build.ArtifactStagingDirectory:" 
      echo "$(Build.ArtifactStagingDirectory)"
      echo "Build.BinariesDirectory:" 
      echo "$(Build.BinariesDirectory)"
      echo "Build.SourcesDirectory:"
      echo "$(Build.SourcesDirectory)"
- task: CmdLine@2
  name: Build
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)/dendrite'
    script: './build.sh'