# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- develop

pool:
  vmImage: ubuntu-latest


steps:
- task: GoTool@0
  inputs:
    version: '1.10'

- task: Bash@3
  displayName: 'Build the executables'
  inputs:
    targetType: 'inline'
    script: './build.sh'
    workingDirectory: '$(Build.SourcesDirectory)'