# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- develop

pool:
  vmImage: ubuntu-latest


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Download v.1.14'
      wget https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz
      sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz
      export PATH=$PATH:/usr/local/go/bin
      go version

- task: Bash@3
  displayName: 'Build the executables'
  inputs:
    targetType: 'inline'
    script: './build.sh'
    workingDirectory: '$(Build.SourcesDirectory)'