{{ if (gt (len (.Files.Glob "appservices/*")) 0) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-appservices-conf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "appservices/*").AsSecrets | indent 2 }}
{{ end }}
{{ if and .Values.configuration.signing_key.create (not .Values.configuration.signing_key.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Chart.Name }}-signing-key
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}

{{- $connectionString := print "postgresql://" .Values.configuration.database.user ":" .Values.configuration.database.password "@" .Values.configuration.database.host }}
{{- if .Values.postgresql.enabled }}
{{- $connectionString = print "postgresql://" .Values.postgresql.auth.username ":" .Values.postgresql.auth.password "@" .Chart.Name -}}
{{ end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
stringData:
  dendrite.yaml: |
    version: 2
    global:
      private_key: /etc/dendrite/secrets/signing.key
      key_id: ed25519:auto
      key_validity_period: {{ .Values.configuration.key_validity_period | quote }}
      database:
        connection_string: {{ $connectionString }}?sslmode=disable
        max_open_conns: {{ default 90 .Values.configuration.database.max_open_conns }}
        max_idle_conns: {{ default 5 .Values.configuration.database.max_idle_conns }}
        conn_max_lifetime: {{ default -1 .Values.configuration.database.conn_max_lifetime }}
      cache:
        max_size_estimated: {{ default "1gb" .Values.configuration.cache.max_size_estimated | quote }}
        max_age: {{ default "1h" .Values.configuration.cache.max_age }}
      well_known_server_name: {{ default "" .Values.configuration.well_known_server_name | quote }}
      well_known_client_name: {{ default "" .Values.configuration.well_known_client_name | quote }}
      trusted_third_party_id_servers:
      {{- toYaml .Values.configuration.trusted_third_party_id_servers | nindent 8 }}
      disable_federation: {{ .Values.configuration.disable_federation }}
      jetstream:
        in_memory: false
        storage_path: /data/jetstream
      metrics:
        {{- toYaml .Values.configuration.metrics | nindent 8 }}
      dns_cache:
        {{- toYaml .Values.configuration.dns_cache | nindent 8 }}
    mscs:
      mscs:
        {{- toYaml .Values.configuration.mscs | nindent 8 }}
    app_service_api:
      config_files:
        {{- range $x, $y := .Files.Glob "appservices/*" }}
          - /etc/dendrite/appservices/{{ base $x }}
        {{ end }}
    client_api:
    {{- with .Values.clientapi }}
      registration_disabled: {{ .registration.disabled }}
      registration_shared_secret: {{ .registration.shared_secret | quote }}
      enable_registration_captcha:  {{ .registration.enable_registration_captcha }}
      recaptcha_public_key: {{ .registration.recaptcha_public_key | quote }}
      recaptcha_private_key: {{ .registration.recaptcha_private_key | quote}}
      recaptcha_bypass_secret: {{ .registration.recaptcha_bypass_secret | quote}}
      recaptcha_siteverify_api: {{ .registration.recaptcha_siteverify_api | quote}}
      {{ end }}
      turn:
        {{- toYaml .Values.configuration.turn | nindent 8 }}
      rate_limiting:
        {{- toYaml .Values.configuration.rate_limiting | nindent 8 }}
    federation_api:
      #federation_certificates: []
      send_max_retries: {{ default 16 .Values.federationapi.send_max_retries }}
      disable_tls_validation: {{ default false .Values.federationapi.disable_tls_validation }}
      key_perspectives:
      - server_name: matrix.org
        keys:
        - key_id: ed25519:auto
          public_key: Noi6WqcDj0QmPxCNQqgezwTlBKrfqehY1u2FyWP9uYw
        - key_id: ed25519:a_RXGa
          public_key: l8Hft5qXKn1vfHrg3p4+W8gELQVo8N13JkluMfmn2sQ 
      prefer_direct_fetch: {{ .Values.federationapi.prefer_direct_fetch }}
    media_api:
      base_path: /data/media_store
      max_file_size_bytes: {{ int (default "10485760" .Values.mediaapi.max_file_size_bytes) }}
      dynamic_thumbnails: {{ .Values.mediaapi.dynamic_thumbnails }}
      max_thumbnail_generators: {{ .Values.mediaapi.max_thumbnail_generators }}
      thumbnail_sizes:
        {{- toYaml .Values.mediaapi.thumbnail_sizes | nindent 8 }}
    room_server:
    sync_api:
      real_ip_header: {{ .Values.syncapi.real_ip_header }}
      search:
        enabled: {{ default false .Values.syncapi.search.enabled }}
        index_path: /data/search
        language: {{ default "en" .Values.syncapi.search.language }}
    tracing:
      {{- toYaml .Values.configuration.tracing | nindent 6 }}
    logging:
    {{- if .Values.configuration.logging }}
    {{- toYaml .Values.configuration.logging | nindent 4 }}
    {{ end }}
