steps:
  - command:
    - "go build ./cmd/..."
    label: ":hammer_and_wrench: Build / :go: 1.11"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"

  - command:
    - "go build ./cmd/..."
    label: ":hammer_and_wrench: Build / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"

  - command:
    - "go test ./..."
    label: ":female-scientist: Unit tests / :go: 1.11"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"

  - command:
    - "go test ./..."
    label: ":female-scientist: Unit tests / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"

  - command:
    # https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint
    - "GOGC=10 ./scripts/find-lint.sh"
    label: ":lower_left_crayon: Lint / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
