steps:
  - command:
    - "go build ./cmd/..."
    label: ":hammer_and_wrench: Build / :go: 1.11"
    env:
      GOGC: "400"
      DENDRITE_LINT_DISABLE_GC: "1"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"

  - command:
    - "go test ./..."
    label: ":female-scientist: Unit tests / :go: 1.11"
    env:
      GOGC: "400"
      DENDRITE_LINT_DISABLE_GC: "1"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"

  - command:
    - "go build ./cmd/..."
    label: ":hammer_and_wrench: Build / :go: 1.12"
    env:
      GOGC: "400"
      DENDRITE_LINT_DISABLE_GC: "1"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"

  - command:
    - "go test ./..."
    label: ":female-scientist: Unit tests / :go: 1.12"
    env:
      GOGC: "400"
      DENDRITE_LINT_DISABLE_GC: "1"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"

  - command:
    - "./scripts/find-lint.sh"
    label: ":lower_left_crayon: Lint / :go: 1.12"
    env:
      GOGC: "400"
      DENDRITE_LINT_DISABLE_GC: "1"
      GO111MODULE: off
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
