// Code generated by "stringer -type=Presence -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PresenceUnavailable-1]
	_ = x[PresenceOnline-2]
	_ = x[PresenceOffline-3]
}

const _Presence_name = "unavailableonlineoffline"

var _Presence_index = [...]uint8{0, 11, 17, 24}

func (i Presence) String() string {
	i -= 1
	if i >= Presence(len(_Presence_index)-1) {
		return "Presence(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Presence_name[_Presence_index[i]:_Presence_index[i+1]]
}
