FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-monolith-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT [ "/usr/bin/dendrite-monolith-server", "--tls-cert=server.crt", "--tls-key=server.key", "--config=dendrite.yaml" ]

EXPOSE 8008
EXPOSE 8448

VOLUME /etc/dendrite