FROM neilalexander/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-federation-sender-server /usr/bin
COPY --from=base /build/docker/services/federation-sender.sh /usr/bin

WORKDIR /usr

ENTRYPOINT ./bin/federation-sender.sh

EXPOSE 7776