FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-media-api-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-media-api-server", "--config=dendrite.yaml"]

EXPOSE 7774

VOLUME /etc/dendrite
VOLUME /var/dendrite/media