FROM neilalexander/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/federation-api-proxy /usr/bin
COPY --from=base /build/docker/services/federation-api-proxy.sh /usr/bin

WORKDIR /usr

ENTRYPOINT ./bin/federation-api-proxy.sh

EXPOSE 8008
EXPOSE 8448