FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-client-api-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-client-api-server", "--config=dendrite.yaml"]

EXPOSE 7771

VOLUME /etc/dendrite