FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-key-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-key-server", "--config=dendrite.yaml"]

EXPOSE 7778

VOLUME /etc/dendrite