FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/federation-api-proxy /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/federation-api-proxy", "--bind-address=:8448", "--federation-api-url=http://federation_api_server:7772", "--media-api-server-url=http://media_api:7774" ]

EXPOSE 8008
EXPOSE 8448

VOLUME /etc/dendrite