FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-federation-sender-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-federation-sender-server", "--config=dendrite.yaml"]

EXPOSE 7776

VOLUME /etc/dendrite