FROM neilalexander/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-federation-api /usr/bin
COPY --from=base /build/docker/services/federation-api.sh /usr/bin

WORKDIR /usr

ENTRYPOINT ./bin/federation-api.sh

EXPOSE 7772