FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-edu-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-edu-server", "--config=dendrite.yaml"]

EXPOSE 7777

VOLUME /etc/dendrite