FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/client-api-proxy /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT [ "/usr/bin/client-api-proxy", "--bind-address=:8008", "--client-api-server-url=http://client_api:7771", "--sync-api-server-url=http://sync_api:7773", "--media-api-server-url=http://media_api:7774", "--public-rooms-api-server-url=http://public_rooms_api:7775" ]

EXPOSE 8008
EXPOSE 8448