FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-room-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-room-server", "--config=dendrite.yaml"]

EXPOSE 7770

VOLUME /etc/dendrite