FROM matrixdotorg/dendrite:latest AS base

FROM alpine:latest

COPY --from=base /build/bin/dendrite-sync-api-server /usr/bin

WORKDIR /etc/dendrite

ENTRYPOINT ["/usr/bin/dendrite-sync-api-server", "--config=dendrite.yaml"]

EXPOSE 7773

VOLUME /etc/dendrite