version: "3.4"
services:
  riot:
    image: vectorim/riot-web
    networks:
      - internal
    ports:
      - "8500:80"

  rendezvous:
    container_name: libp2p-rendezvous
    hostname: rendezvous
    image: libp2p/websocket-star-rendezvous
    networks:
      - internal
    ports:
      - "443:443"
      - "9090:9090"

  monolith-1:
    container_name: dendrite_monolith-1
    hostname: monolith-1
    entrypoint: ["bash", "./docker/services/p2p-demo.sh"]
    build: ./
    volumes:
      - ..:/build
      - ./build/bin:/build/bin
      - ~/go/pkg:/go/pkg
    networks:
      - internal
    ports:
      - "8080:8080"
      - "8008:8008"
      - "8448:8448"

  monolith-2:
    container_name: dendrite_monolith-2
    hostname: monolith-2
    entrypoint: ["bash", "./docker/services/p2p-demo.sh"]
    build: ./
    volumes:
      - ..:/build
      - ./build/bin:/build/bin
      - ~/go/pkg:/go/pkg
      - ~/Desktop/dendrite-configs:/etc/dendrite
    networks:
      - internal
    ports:
      - "8081:8080"
      - "8009:8008"
      - "8449:8448"

networks:
  internal:
    attachable: true
