#! /bin/bash

set -eu

echo "Looking for lint..."
GOPATH="$(pwd):$(pwd)/vendor" gometalinter --config=linter.json ./...

echo "Double checking spelling..."
misspell -error src *.md

echo "Testing..."
gb test

# Check that all the packages can build.
# When `go build` is given multiple packages it won't output anything, and just
# checks that everything builds. This seems to do a better job of handling
# missing imports than `gb build` does.
echo "Double checking it builds..."
GOPATH=$(pwd):$(pwd)/vendor go build github.com/matrix-org/dendrite/cmd/...

echo "Done!"
