{
 "title": "Dendrite",
 "description": "Dendrite dashboard from https://github.com/matrix-org/dendrite/",
 "tags": [
  "matrix",
  "dendrite"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "bucket_size", "label": "Bucket Size", "query": "30s,1m,2m,5m,10m,15m" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dendrite_caching_in_memory_lru_roominfo, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dendrite_caching_in_memory_lru_roominfo, job)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(dendrite_caching_in_memory_lru_roominfo, index)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
     "legendFormat": "{{job}}-{{index}} "
    }
   ]
  },
  {
   "title": "Registerd Users",
   "type": "stat",
   "description": "Total number of registered users",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dendrite_clientapi_reg_users_total",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Sync API",
   "type": "graph",
   "description": "The number of sync requests that are active right now and are waiting to be woken by a notifier",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dendrite_syncapi_active_sync_requests{instance=\"$instance\"}[$bucket_size]))without (job,index)",
     "legendFormat": "active"
    },
    {
     "expr": "sum(rate(dendrite_syncapi_waiting_sync_requests{instance=\"$instance\"}[$bucket_size]))without (job,index)",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Sendevent Duration",
   "type": "heatmap",
   "description": "How long it takes to build and submit a new event from the client API to the roomserver",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dendrite_clientapi_sendevent_duration_millis_bucket{action=\"build\",instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Federation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Federation Sender Destination",
   "type": "graph",
   "description": "Collection of queues for sending transactions to other matrix servers",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dendrite_federationsender_destination_queues_running",
     "legendFormat": "Queue Running"
    },
    {
     "expr": "dendrite_federationsender_destination_queues_total",
     "legendFormat": "Queue Total"
    },
    {
     "expr": "dendrite_federationsender_destination_queues_backing_off",
     "legendFormat": "Backing Off"
    }
   ]
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Room Event Processing",
   "type": "heatmap",
   "description": "How long it takes the roomserver to process an event",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(dendrite_roomserver_processroomevent_duration_millis_bucket{instance=\"$instance\"}[$bucket_size])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Server Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dendrite_caching_in_memory_lru_server_key",
     "legendFormat": "Server keys"
    }
   ]
  },
  {
   "title": "Federation Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dendrite_caching_in_memory_lru_federation_event",
     "legendFormat": "Federation Event"
    }
   ]
  },
  {
   "title": "Room IDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dendrite_caching_in_memory_lru_roomserver_room_ids",
     "legendFormat": "Room IDs"
    }
   ]
  }
 ]
}