image:
  # -- Docker repository/image to use
  name: "ghcr.io/matrix-org/dendrite-monolith:v0.10.8"
  # -- Kubernetes pullPolicy
  pullPolicy: IfNotPresent


# signing key to use
signing_key:
  # -- Create a new signing key, if not exists
  create: true
  # -- Use an existing secret
  existingSecret: ""

# -- Default resource requests/limits.
# @default -- sets some sane default values
resources:
  requests:
    memory: "512Mi"

  limits:
    memory: "4096Mi"

persistence:
  storageClass: ""
  jetstream:
    # -- Use an existing volume claim for jetstream
    existingClaim: ""
    capacity: "1Gi"
  media:
    # -- Use an existing volume claim for media files
    existingClaim: ""
    capacity: "1Gi"
  search:
    # -- Use an existing volume claim for the fulltext search index
    existingClaim: ""
    capacity: "1Gi"


global:
  # -- Servername for this Dendrite deployment
  server_name: ""

  # -- The server name to delegate server-server communications to, with optional port
  # e.g. localhost:443
  well_known_server_name: ""

  # -- The server name to delegate client-server communications to, with optional port
  # e.g. localhost:443
  well_known_client_name: ""

  # -- Lists of domains that the server will trust as identity servers to verify third
  # party identifiers such as phone numbers and email addresses.
  trusted_third_party_id_servers:
    - matrix.org
    - vector.im

  # -- Disable federation. Dendrite will not be able to make any outbound HTTP requests
  # to other servers and the federation API will not be exposed.
  disable_federation: false

  key_validity_period: 168h0m0s

  database:
    # -- Default database host
    host: ""
    # -- Default database user
    user: ""
    # -- Default database password
    password: ""

    # -- Default database maximum open connections
    max_open_conns: 90
    # -- Default database maximum idle connections
    max_idle_conns: 5
    # -- Default database maximum lifetime
    conn_max_lifetime: -1

  cache:
    # -- The estimated maximum size for the global cache in bytes, or in terabytes,
    # gigabytes, megabytes or kilobytes when the appropriate 'tb', 'gb', 'mb' or
    # 'kb' suffix is specified. Note that this is not a hard limit, nor is it a
    # memory limit for the entire process. A cache that is too small may ultimately
    # provide little or no benefit.
    max_size_estimated: 1gb
    # -- The maximum amount of time that a cache entry can live for in memory before
    # it will be evicted and/or refreshed from the database. Lower values result in
    # easier admission of new cache entries but may also increase database load in
    # comparison to higher values, so adjust conservatively. Higher values may make
    # it harder for new items to make it into the cache, e.g. if new rooms suddenly
    # become popular.
    max_age: 1h

  # -- Configures phone-home statistics reporting. These statistics contain the server
  # name, number of active users and some information on your deployment config.
  # We use this information to understand how Dendrite is being used in the wild.
  report_stats:
    enabled: false
    endpoint: https://matrix.org/report-usage-stats/push

  # -- Configures the handling of presence events. Inbound controls whether we receive
  # presence events from other servers, outbound controls whether we send presence
  # events for our local users to other servers.
  presence:
    enable_inbound: false
    enable_outbound: false

  # -- Server notices allows server admins to send messages to all users on the server.
  server_notices:
    enabled: false
    # The local part, display name and avatar URL (as a mxc:// URL) for the user that
    # will send the server notices. These are visible to all users on the deployment.
    local_part: "_server"
    display_name: "Server Alerts"
    avatar_url: ""
    # The room name to be used when sending server notices. This room name will
    # appear in user clients.
    room_name: "Server Alerts"

  # prometheus metrics
  metrics:
    # -- Whether or not Prometheus metrics are enabled.
    enabled: false
    # HTTP basic authentication to protect access to monitoring.
    basic_auth:
      # -- HTTP basic authentication username
      user: "metrics"
      # -- HTTP basic authentication password
      password: metrics

  dns_cache:
    # -- Whether or not the DNS cache is enabled.
    enabled: false
    # -- Maximum number of entries to hold in the DNS cache
    cache_size: 256
    # -- Duration for how long DNS cache items should be considered valid ([see time.ParseDuration](https://pkg.go.dev/time#ParseDuration) for more)
    cache_lifetime: "10m"

  # -- Default logging configuration
  # @default -- [default dendrite config values](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml)
  logging:
    - type: std
      level: info

  # -- Default tracing configuration
  # @default -- disabled
  tracing:
    enabled: false
    jaeger:
      serviceName: ""
      disabled: false
      rpc_metrics: false
      tags: []
      sampler: null
      reporter: null
      headers: null
      baggage_restrictions: null
      throttler: null

  profiling:
    # -- Enable pprof. You will need to manually create a port forwarding to the deployment to access PPROF,
    # as it will only listen on localhost and the defined port.
    # e.g. `kubectl port-forward deployments/dendrite 65432:65432`
    enabled: false
    # -- pprof port, if enabled
    port: 65432

  # -- Configuration for experimental MSC's. (Valid values are: msc2836 and msc2946)
  mscs:
    - msc2946
    # A list of enabled MSC's
    # Currently valid values are:
    # - msc2836    (Threading, see https://github.com/matrix-org/matrix-doc/pull/2836)
    # - msc2946    (Spaces Summary, see https://github.com/matrix-org/matrix-doc/pull/2946)

clientapi:
  # -- Prevents new users from being able to register on this homeserver, except when
  # using the registration shared secret below.
  registration_disabled: true

  # Prevents new guest accounts from being created. Guest registration is also
  # disabled implicitly by setting 'registration_disabled' above.
  guests_disabled: true

  # -- If set, allows registration by anyone who knows the shared secret, regardless of
  # whether registration is otherwise disabled.
  shared_secret: ""

  # -- enable reCAPTCHA registration
  enable_registration_captcha: false
  # -- reCAPTCHA public key
  recaptcha_public_key: ""
  # -- reCAPTCHA private key
  recaptcha_private_key: ""
  # -- reCAPTCHA bypass secret
  recaptcha_bypass_secret: ""
  recaptcha_siteverify_api: ""

  # TURN server information that this homeserver should send to clients.
  turn:
    # -- Duration for how long users should be considered valid ([see time.ParseDuration](https://pkg.go.dev/time#ParseDuration) for more)
    turn_user_lifetime: "24h"
    turn_uris: []
    turn_shared_secret: ""
    # -- The TURN username
    turn_username: ""
    # -- The TURN password
    turn_password: ""

  rate_limiting:
    # -- Enable rate limiting
    enabled: true
    # -- After how many requests a rate limit should be activated
    threshold: 20
    # -- Cooloff time in milliseconds
    cooloff_ms: 500
    # -- Users which should be exempt from rate limiting
    exempt_user_ids:

federationapi:
  send_max_retries: 16
  # -- Disable TLS validation
  disable_tls_validation: false
  prefer_direct_fetch: false


mediaapi:
  # -- The max file size for uploaded media files
  max_file_size_bytes: "10485760"
  # Whether to dynamically generate thumbnails if needed.
  dynamic_thumbnails: false
  # -- The maximum number of simultaneous thumbnail generators to run.
  max_thumbnail_generators: 10
  # -- A list of thumbnail sizes to be generated for media content.
  # @default -- [default dendrite config values](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml)
  thumbnail_sizes:
  - width: 32
    height: 32
    method: crop
  - width: 96
    height: 96
    method: crop
  - width: 640
    height: 480
    method: scale

syncapi:
  # -- This option controls which HTTP header to inspect to find the real remote IP
  # address of the client. This is likely required if Dendrite is running behind
  # a reverse proxy server.
  real_ip_header: X-Real-IP
  # -- Configuration for the full-text search engine.
  search:
    # -- Whether or not search is enabled.
    enabled: false
    # -- The language most likely to be used on the server - used when indexing, to
    # ensure the returned results match expectations. A full list of possible languages
    # can be found [here](https://github.com/matrix-org/dendrite/blob/76db8e90defdfb9e61f6caea8a312c5d60bcc005/internal/fulltext/bleve.go#L25-L46)
    language: "en"

postgresql:
  # -- Enable and configure postgres as the database for dendrite.
  # @default -- See value.yaml
  enabled: false
  image:
    repository: bitnami/postgresql
    tag: "15.1.0"
  auth:
    username: dendrite
    password: changeme
    database: dendrite

  persistence:
    enabled: false

ingress:
  # -- Create an ingress for a monolith deployment
  enabled: false
  hosts: []
  className: ""
  hostName: ""
  # -- Extra, custom annotations
  annotations: {}

  tls: []

service:
  type: ClusterIP
  port: 80
