title: Dendrite
description: >-
  Second-generation Matrix homeserver written in Go!
baseurl: "/dendrite" # the subpath of your site, e.g. /blog
url: ""
twitter_username: matrixdotorg
github_username: matrix-org
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
aux_links:
  "GitHub":
    - "//github.com/matrix-org/dendrite"
aux_links_new_tab: true
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - INSTALL.md
