steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dendrite-monolith:$TAG', '-f', 'build/docker/Dockerfile.monolith', '.']
  - name: gcr.io/cloud-builders/kubectl
    args: ['set', 'image', 'deployment/dendrite', 'dendrite=gcr.io/$PROJECT_ID/dendrite-monolith:$TAG']
    env:
      - CLOUDSDK_CORE_PROJECT=globekeeper-production
      - CLOUDSDK_COMPUTE_ZONE=europe-west2-a
      - CLOUDSDK_CONTAINER_CLUSTER=synapse-production
images:
  - gcr.io/$PROJECT_ID/dendrite-monolith:$TAG
timeout: 360s
