ARG builder
ARG TARGETARCH

# https://stackoverflow.com/a/63472135/3551604
FROM ${TARGETARCH}/${builder}:latest as builder

FROM alpine:latest

ARG DENDRITE_BINARY

ENV DENDRITE_BINARY=${DENDRITE_BINARY}

COPY --from=builder /build/bin/* /usr/bin/

VOLUME /etc/dendrite
WORKDIR /etc/dendrite

ENTRYPOINT "/usr/bin/${DENDRITE_BINARY}"
