FROM alpine:latest

ARG DENDRITE_BINARY=
ARG BIN_DIRECTORY=
ENV DENDRITE_BINARY=${DENDRITE_BINARY}

COPY --from=builder /build/bin/* /usr/bin

VOLUME /etc/dendrite
WORKDIR /etc/dendrite

ENTRYPOINT "/usr/bin/${DENDRITE_BINARY}"
